name: Set up MATLAB integration test cases
on:
  workflow_run:
    workflows: ["Test Runner"]
    branches: [main]
    types: [completed]
jobs:
  Build_fails_when_MATLAB_is_not_setup:
    continue-on-error: true
    name: Build without MATLAB
    runs-on: ubuntu-latest
    steps:
      - name: Run command
        uses: matlab-actions/run-command@v0
        with:
          command: version

  Release_is_picked:
    continue-on-error: true
    name: User specified MATLAB release is picked
    runs-on: ubuntu-latest
    steps:
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
        with:
          release: R2020b