name: Set up MATLAB integration test cases
on: 
  workflow_run: 
    workflows: ["Test Runner"]
    branches: [main]
    types: [completed]
jobs:
  Build_fails_when_MATLAB_is_not_setup:
    continue-on-error: true
    name: Build without MATLAB
    runs-on: ubuntu-latest
    steps:
#       - name: Run command
#         env:
#              tag: v0
#              run-command: matlab-actions/run-command${{env.tag}}
#         uses: ${{env.run-command}}
#         with:
#           command: version
      - name: print
        env:
             tag: v0
             run-command: matlab-actions/run-command@${tag}
        run: |
          echo ${{env.run-command}}
          echo ${{env.tag}}

  Release_is_picked:
    continue-on-error: true
    name: User specified MATLAB release is picked
    runs-on: ubuntu-latest
    steps:
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
        with:
          release: R2020b
